BDX-town/Mangane

app/soapbox/components/thumb_navigation.js, app/soapbox/features/ui/components/tabs_bar.js, app/styles/components/icon.scss, app/styles/components/tabs-bar.scss
Fix https://github.com/Cl0v1s/mangane-ui/issues/12
=> [CH] Add local and fediverse timeline in thumb menu, move serach icon in top navigation

app/soapbox/features/follow_requests/components/account_authorize.tsx
Fix https://github.com/Cl0v1s/mangane-ui/issues/22
=> [CH] Change buttons order in follow request ui

app/soapbox/components/sidebar-navigation.tsx, app/soapbox/components/sidebar_menu.tsx, app/soapbox/features/conversations/index.tsx, app/soapbox/features/direct_timeline/index.tsx
Fix https://github.com/Cl0v1s/mangane-ui/issues/21
=> [CH] Add direct messages entries in menus, update direct message screen

app/soapbox/__fixtures__/intlMessages.json, app/soapbox/actions/settings.ts, app/soapbox/features/enlistment/enlistment.tsx, app/soapbox/features/enlistment/steps/step0.tsx, app/soapbox/features/enlistment/steps/step1.tsx, app/soapbox/features/enlistment/steps/step2.tsx, app/soapbox/features/enlistment/steps/step3.tsx, app/soapbox/features/enlistment/steps/step4.tsx, app/soapbox/features/preferences/index.tsx, app/soapbox/features/ui/index.tsx, app/soapbox/locales/fr.json, app/styles/application.scss, app/styles/components/enlistment.scss
Fix https://github.com/Cl0v1s/mangane-ui/issues/9
=> [ADD] Add onboarding for new user explaining how the instance works 

app/soapbox/components/sidebar_menu.tsx
Fix https://github.com/Cl0v1s/mangane-ui/issues/30
=> [ADD] Add follow request entry on side menu on mobile

webpack/development.js, webpack/shared.js
Partially fix https://github.com/Cl0v1s/mangane/issues/42
=> [FIX] Fix errors on test on production ci build

app/soapbox/components/status.tsx
Fix https://github.com/BDX-town/Mangane/issues/74
=> [FIX] use actualStatus hidden state boosted status with CW are now working correctly

app/soapbox/actions/admin.ts, app/soapbox/locales/fr.json
https://github.com/BDX-town/Mangane/issues/75
=> [FIX]  Internal server error when accessing the report tab on dashboard

app/soapbox/components/account.tsx, app/soapbox/components/ui/emoji-react/emoji-react.tsx, app/soapbox/components/ui/index.ts, app/soapbox/features/notifications/components/notification.tsx, app/soapbox/features/status/components/status-interaction-bar.tsx, app/soapbox/features/ui/components/reactions_modal.tsx, app/soapbox/normalizers/notification.ts, app/soapbox/reducers/user_lists.ts, app/soapbox/utils/emoji_reacts.ts
Fix https://github.com/BDX-town/Mangane/issues/90
=> [ADD] Add support for custom emoji reaction (misskey for example, and probably akkoma itself)

app/soapbox/features/soapbox_config/index.tsx
Fix https://github.com/BDX-town/Mangane/issues/95
Fix https://github.com/BDX-town/Mangane/issues/98
=> [FIX] Fix crash when adding footer link

app/soapbox/features/directory/components/account_card.tsx, app/soapbox/features/directory/index.tsx, app/soapbox/locales/fr.json
Fix https://github.com/BDX-town/Mangane/issues/88
=> [FIX] Fix missing translation in directory + fix wrong text when yesterday

app/soapbox/utils/features.ts
Fix https://github.com/BDX-town/Mangane/issues/106
=> [FIX] Hide scheduledStatuses button since it doesnt work on pleroma

app/soapbox/features/scheduled_statuses/builder.tsx, app/soapbox/features/scheduled_statuses/components/scheduled_status.tsx
Fix https://github.com/BDX-town/Mangane/issues/71
=> [FIX] Fix crash when deleting scheduled post

app/soapbox/features/compose/components/search_results.tsx, app/soapbox/reducers/search.ts
Fix https://github.com/BDX-town/Mangane/issues/70
=> [FIX] Fix bug when changing search tab + change tabs order to search on statuses by default

app/soapbox/features/status/components/thread-login-cta.tsx, app/soapbox/features/ui/components/panels/sign-up-panel.tsx, app/soapbox/locales/fr.json, app/soapbox/pages/default_page.tsx, app/soapbox/pages/home_page.tsx, app/soapbox/pages/profile_page.tsx, app/soapbox/pages/status_page.tsx
Relates to https://github.com/BDX-town/Mangane/issues/69
=> [REM] Remove banner, signup prompts are only availalble if registrations are enabled

app/soapbox/components/sidebar_menu.tsx, app/soapbox/features/settings/index.tsx, app/soapbox/features/ui/components/link_footer.tsx, app/soapbox/locales/fr.json
Relates to https://github.com/BDX-town/Mangane/issues/69
=> [CH] Move content settings into ... settings

app/soapbox/features/chats/components/chat-box.tsx, app/styles/chats.scss
Fix https://github.com/BDX-town/Mangane/issues/4
=> [ADD] Add emoji picker on chats

app/soapbox/components/ui/modal/modal.tsx, app/soapbox/features/compose/components/emoji_picker.tsx, app/soapbox/features/compose/components/emoji_picker_menu.js, app/soapbox/features/compose/containers/emoji_picker_dropdown_container.js, app/styles/emoji_picker.scss
Fix https://github.com/BDX-town/Mangane/issues/96
Fix https://github.com/BDX-town/Mangane/issues/61
=> [CH] Better emoji selection on mobile, fix hover priority

app/soapbox/features/public_timeline/index.tsx, app/soapbox/features/status/components/detailed-status.tsx, app/soapbox/locales/fr.json
Fix https://github.com/BDX-town/Mangane/issues/139
=> [FIX] translation and bubble timeline are now accessible for auth users only

app/soapbox/features/soapbox_config/index.tsx, app/soapbox/features/ui/index.tsx, app/soapbox/reducers/soapbox.js
Fix https://github.com/BDX-town/Mangane/issues/99
=> [FIX] default configuration is now equal to what's shown in ui

app/soapbox/components/polls/poll-footer.tsx, app/soapbox/components/polls/poll-option.tsx
Fix https://github.com/BDX-town/Mangane/issues/154
=> [REM] Remove usage of voters_count for polls which seems to be broken on pleroma/akkoma

docs/administration/akkoma.md, docs/administration/updating.md, docs/contributing.md, docs/customization.md, docs/history.md
- History: Mangane not Soapbox
- Akkoma: add more supported features
- Upgrade: more precise instructions
=> [CH] Better documentation

README.md
- Reorganize document sections
- Add upgrade instruction
- Warning about usage with Mastodon
- Information about installation with Yunohost
=> [CH] Better doc for Upgrade, Mastodon, Yunohost and more

app/soapbox/features/account/components/header.tsx
=> [ADD] Open original profile button

app/soapbox/components/sidebar_menu.tsx
Original work from @uandreew here: https://github.com/BDX-town/Mangane/pull/203/commits
=> [ADD] add "admin dashboard" to sidebar menu on mobile (#203)

docs/contributing.md, docs/customization.md
Fix https://github.com/BDX-town/Mangane/issues/190
=> [CH] Remove mention to soapbox in some doc files

app/soapbox/actions/import_data.ts
Fix https://github.com/BDX-town/Mangane/issues/206
=> [FIX] Fix wrong routes on imports 

docs/custom_reactions_emoji.md
=> [ADD] Custom emoji installation documentation 

app/soapbox/features/settings/index.tsx, app/soapbox/features/ui/index.tsx
Fix https://github.com/BDX-town/Mangane/issues/196
=> [CH] Remove settings password options when using ldap

app/soapbox/reducers/compose.ts
Fix following issue:
1) Open compose modal
2) Privacy is correct
3) Close compose modal
4) Open compose modal
5) Privacy isnt ok anymore
=> [FIX] Fix wrong default privacy after first compose modal

app/soapbox/components/status.tsx, app/soapbox/features/compose/components/compose_form.js, app/soapbox/features/compose/containers/compose_form_container.js, app/soapbox/reducers/compose.ts
Fix https://github.com/BDX-town/Mangane/issues/225
New behavior: 
When quote, copy status CW and disable CW edition. 
When actual status is hidden, quoted content is hidden too.
=> [FIX] Fix Quoted status CW not being forwarded nor hidden

app/styles/components/snackbar.scss
Fix https://github.com/BDX-town/Mangane/issues/188
=> [CH] Change error icon to avoid close confusion

app/soapbox/features/edit_profile/index.tsx, app/soapbox/features/followers/index.js, app/soapbox/features/following/index.js, app/soapbox/features/ui/components/profile_stats.tsx, app/soapbox/locales/fr.json
=> fix: fix unresponsive hide_network toggle in profile + hide followers accordingly

app/soapbox/utils/features.ts
is in develop branch, but as people -me- starts to use it...
as the title says... this should be available for pleroma now too :)
=> feat: pleroma now can follow hashtags too

app/soapbox/features/ui/components/profile_stats.tsx, app/soapbox/locales/fr.json
fix https://github.com/BDX-town/Mangane/issues/354
=> fix: even with counts hidden we should be able to see our own followee counts

app/soapbox/components/status.tsx, app/soapbox/components/status_list.tsx, app/soapbox/features/followed_tags/index.tsx, app/soapbox/features/placeholder/components/placeholder_status.tsx, app/soapbox/features/status/components/thread-status.tsx, app/soapbox/features/status/index.tsx
fix https://github.com/BDX-town/Mangane/issues/381
=> fix: various ui fixes after last release

app/soapbox/components/status-action-bar.tsx
fix https://github.com/BDX-town/Mangane/issues/390
=> fix: action bar icons are not centered

app/soapbox/features/ui/index.tsx
fix https://github.com/BDX-town/Mangane/issues/402
=> fix: hide fab on compose page
